/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'esuarez' at '15/12/16 07:47 PM' with Gradle 2.14.1
 *
 * @author esuarez, @date 15/12/16 07:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
